# Use Google's official Flutter Docker image
image: ghcr.io/cirruslabs/flutter:stable

stages:
  - build

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

# Define cache to speed up builds
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .pub-cache/
    - .dart_tool/
    - build/
    - .gradle/

android_debug:
  stage: build
  before_script:
    # Show Flutter version for debugging purposes
    - flutter --version
    # Make sure we have the latest dependencies
    - flutter pub get
  script:
    # Build debug APK
    - flutter build apk --debug
  artifacts:
    paths:
      - build/app/outputs/flutter-apk/app-debug.apk
    expire_in: 1 week
  tags:
    - docker