# Use Cirrus Labs' Android SDK Docker image version 35
image: ghcr.io/cirruslabs/android-sdk:35

stages:
  - build

variables:
  # Disable Gradle daemon for CI environment
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.jvmargs=-Xmx2048m"
  # Define cache locations
  PUB_CACHE: "$CI_PROJECT_DIR/.pub-cache"
  
# Optimize cache to speed up builds
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .pub-cache/
    - build/
    - .gradle/
    - .dart_tool/
    - android/.gradle/

build_debug_apk:
  stage: build
  before_script:
    # Display environment information for debugging
    - flutter --version
    - java -version
    
    # Install Flutter dependencies
    - flutter pub get
    
    # Ensure gradlew is executable
    - chmod +x android/gradlew
    
  script:
    # Clean build to avoid cached issues
    - flutter clean
    
    # Build debug APK (no tree shaking for faster builds)
    - flutter build apk --debug
    
  artifacts:
    name: "debug-apk-${CI_COMMIT_SHORT_SHA}"
    paths:
      - build/app/outputs/flutter-apk/app-debug.apk
    expire_in: 2 weeks