image: ghcr.io/cirruslabs/flutter:stable

cache:
  paths:
    - .dart_tool/
    - .pub-cache/
    - android/.gradle/

build_apk:
  stage: build
  script:
    - flutter pub get
    - flutter build apk --debug  # Note: this builds a debug version, not suitable for production
  artifacts:
    paths:
      - build/app/outputs/apk/debug/app-debug.apk
    expire_in: 1 week