image: mobiledevops/flutter-sdk-image:latest
variables:
  OUTPUT_DIR: "build/app/outputs/flutter-apk"

stages:
  - build

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .pub-cache/
    - .gradle/
    - .dart_tool/
    - build/
    - $HOME/.pub-cache/
    - $HOME/.gradle/

flutter_build:
  stage: build
  before_script:
    - flutter --version
    - chmod +x android/gradlew
    - flutter pub get
    - flutter config --no-analytics
  script:
    - flutter build apk --release --split-per-abi
  after_script:
    - rm -rf $HOME/.gradle/daemon/
    - rm -rf .gradle/daemon/
  artifacts:
    paths:
      - $OUTPUT_DIR/app-armeabi-v7a-release.apk
      - $OUTPUT_DIR/app-arm64-v8a-release.apk
      - $OUTPUT_DIR/app-x86_64-release.apk
    expire_in: 1 week