image: flutter:stable

variables:
  PUB_CACHE: "/root/.pub-cache"

cache:
  key: ${CI_PROJECT_ID}
  paths:
    - .pub-cache/
    - .flutter-plugins
    - .flutter-plugins-dependencies
    - pubspec.lock

stages:
  - build

before_script:
  - flutter pub get
  - yes | sdkmanager --licenses || true
  - flutter doctor

build_debug_apk:
  stage: build
  script:
    - flutter build apk --debug
  artifacts:
    paths:
      - build/app/outputs/apk/debug/app-debug.apk
    expire_in: 1 week