image: mobiledevops/flutter-sdk-image:latest

variables:
  OUTPUT_DIR: "build/app/outputs/flutter-apk"

stages:
  - build

# Cache Flutter dependencies to speed up builds
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .pub-cache/
    - .gradle/
    - .dart_tool/
    - build/

flutter_build:
  stage: build
  before_script:
    - flutter --version
    - if [ -f "android/gradlew" ]; then chmod +x android/gradlew; fi
    - flutter pub get
  script:
    - flutter build apk --release --split-per-abi
  artifacts:
    paths:
      - $OUTPUT_DIR/app-armeabi-v7a-release.apk
      - $OUTPUT_DIR/app-arm64-v8a-release.apk
      - $OUTPUT_DIR/app-x86_64-release.apk
    expire_in: 1 week