# Use the official Flutter Docker image
image: cirrusci/flutter:stable

# Cache dependencies between builds
cache:
  paths:
    - .pub-cache/
    - .dart_tool/
    - build/
    - .gradle/

stages:
  - build

variables:
  # Avoid downloading the Gradle wrapper again
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.caching=true"

before_script:
  # Make sure we have the latest dependencies
  - flutter pub get
  # Show Flutter version for debugging purposes
  - flutter --version

build_android_debug:
  stage: build
  script:
    # Build debug APK
    - flutter build apk --debug
  artifacts:
    paths:
      - build/app/outputs/flutter-apk/app-debug.apk
    expire_in: 1 week
  # Trigger this job only for changes to these directories
  only:
    changes:
      - lib/**/*
      - pubspec.yaml
      - android/**/*
      - .gitlab-ci.yml